server:
  port: "8080"

log:
  level: "info"
  max_size_mb: 100
  max_backups: 5
  max_age_days: 30
  compress: true
  log_dir: "/logs"

llm:
  server: "http://127.0.0.1:5000/completions"
  schema_dir: "config/schemas"

results:
  dir: "results"